/**
 * Shared controller context (generated by scripts/split-controller.js).
 *
 * Holds the common requires, Sequelize model handles and helper functions that
 * every domain controller extracted from the old monolith depends on. Domain
 * controllers destructure what they need from here.
 */
const db = require("../../../app/models/index");
const jwt = require("jsonwebtoken");
const authConfig = require("../../../app/config/authConfig");
const path = require("path");
const fs = require("fs").promises;
const fsSync = require("fs");
const { v4: uuidv4 } = require('uuid');

const hasMeaningfulPreviousPolicyData = (policy) => {
    if (!policy || typeof policy !== 'object') {
        return false;
    }

    const fieldsToCheck = [
        'PolicyNumber',
        'PolicyFrom',
        'PolicyTo',
        'PolicyIssuedDate',
        'CompanyName',
        'SumInsured',
        'PremiumAmount',
        'NoClaimBonus',
        'RenewDate',
        'PdfFile',
        'PdfFileName',
        'ClaimStatementPDFfile',
        'ClaimStatementPDFfileName',
        'PreviousPolicyNumber',
        'NomineeName',
        'NomineeRelation',
        'NomineeDob',
        'NomineeAge',
        'AddOnCover',
        'ClaimExpireInPolicy',
        'PreviousAgentName',
        'PreviousAgentCode',
        'PreviousAgentContactNumber'
    ];

    return fieldsToCheck.some((field) => {
        const value = policy[field];

        if (value === null || value === undefined) {
            return false;
        }

        if (typeof value === 'string') {
            return value.trim() !== '';
        }

        if (typeof value === 'number') {
            return !isNaN(value);
        }

        if (typeof value === 'boolean') {
            return true;
        }

        return !!value;
    });
};

// Helper function to create notifications
const createNotification = async (notificationData) => {
    try {
        const notification = await db.notification.create({
            title: notificationData.title,
            message: notificationData.message,
            type: notificationData.type, // 'vehicle', 'mediclaim', 'loan', 'builder', 'system'
            category: notificationData.category, // 'user_added', 'user_updated', etc.
            user_id: notificationData.user_id || null,
            target_user_id: notificationData.target_user_id || null,
            record_id: notificationData.record_id || null,
            is_important: notificationData.is_important || false,
            metadata: notificationData.metadata || null
        });
        console.log('🔔 [NOTIFICATION] Created:', notification.title);
        return notification;
    } catch (error) {
        console.error('❌ [NOTIFICATION] Error creating notification:', error);
        return null;
    }
};
const User = db.user;
const Inqueryuser = db.inqueryuser;
const loanConfiguration = db.loanConfiguration;
const RunningPolicies = db.runningPolicyMediclaim;
const PreviousPolicies = db.previousPolicyMediclaim;
const BuilderUser = db.builderUser;
const BuildingManager = db.buildingManager;
const DocumentSelectedLoan = db.documentSelectedLoan;
const DisbursementLoan = db.disbursementLoan;
const PartPaymentLoan = db.partPaymentLoan;
const codeDetail = db.codeDetail;
const vehicles = db.vehicles;
const references = db.references;
const documents = db.documents;
const policyPlan = db.policyPlan;
const vehicleUser = db.vehicleUser;
const vehcileRunningPolicy = db.vehcileRunningPolicy;
// Merged into the unified policy table (is_current flag). Aliased to the same model
// so any leftover read/include still resolves; the previousPolicies association is scoped.
const vehiclePreviousPolicy = db.vehcileRunningPolicy;
const vehicle_document = db.vehicle_document;
const policyType = db.policyType;
const companyType = db.companyType;
const LoginLoan = db.loginLoan;
const property = db.property;
const SanctionLoan = db.sanctionLoan;
const QueryLoan = db.queryLoan;
const CancelLoan = db.cancelLoan;
const Category = db.category;
const MediclaimCompany = db.mediclaimCompany;
const unit_category_list = db.unit_category_list;
const MediclaimProduct = db.mediclaimProduct;
const userCatergory = db.userCategory;
const Unit = db.unit;
const UnitCategoryDetail = db.unit_category_detail;
const builderConsumer = db.builderConsumer;
const consumerRoleMapping = db.consumerRoleMapping;
const UnitCategoryList = db.unit_category_list;
const FamilyMember = db.familyMember;
const loanUser = db.loanUser;
const Disburse = db.disburse;
const Mediclaim = db.medicliamuser;
const EmployeeMediclaim = db.employeeMediclaim;
const floor = db.floor;
const Wing = db.wing;
const Blog = db.blog;
const LifeInsurance = db.lifeInsurance;
const LifeInsuranceDocument = db.lifeInsuranceDocument;
const Sequelize = require("sequelize");
const Op = Sequelize.Op;
const moment = require("moment");
const nodemailer = require("nodemailer");
const fsExtra = require("fs-extra");
const dotenvParseVariables = require("dotenv-parse-variables");
let env = require('dotenv').config();
env = dotenvParseVariables(env.parsed);

// NOTE: Auth/login endpoints now live in src/modules/auth. This handler is no
// longer routed. It previously leaked the entire process.env; that has been
// removed. Kept only to avoid breaking any stale references.

// Original controllers directory, so __dirname-relative upload/download paths
// keep resolving to Backend/uploads exactly as before the split.
const CTRL_DIR = path.join(__dirname, "../../../app/controllers");

/**
 * Universal de-dup helper: ensure a consumer→category mapping exists, creating
 * it only if missing. Use this EVERYWHERE a consumer is assigned to a vertical
 * (consumer/vehicle/loan/mediclaim/life pages) so the same person+category can
 * never get a duplicate mapping, regardless of which path created them.
 */
async function ensureCategoryMapping(user_consumer_id, category_id, user_role_id) {
  if (!user_consumer_id || !category_id) return null;
  const [row] = await consumerRoleMapping.findOrCreate({
    where: { user_consumer_id, category_id },
    defaults: { user_consumer_id, category_id, user_role_id: user_role_id || null },
  });
  return row;
}

/**
 * Universal file-upload helper. Saves one express-fileupload file object to the
 * shared uploads dir and returns the stored filename. Use this EVERYWHERE a file
 * is uploaded (consumer docs, vehicle RC, life docs, blog images…) instead of
 * re-implementing mv()/writeFile per controller.
 */
/**
 * Save an uploaded file into a per-module subfolder under /uploads and return
 * the stored path RELATIVE to /uploads (e.g. "vehicle/<uuid>-rc.pdf"), so files
 * are organised by area (consumer-kyc, vehicle, …). The download URL is
 * BASE_URL/uploads/<that path>.
 */
async function saveUpload(fileObj, subdir = "misc") {
  if (!fileObj) return null;
  const safeSub = String(subdir).replace(/[^a-z0-9/_-]/gi, "") || "misc";
  const dir = path.join(CTRL_DIR, "../../uploads", safeSub);
  await fsExtra.ensureDir(dir);
  const uniqueName = `${uuidv4()}-${path.basename(fileObj.name)}`;
  const uploadPath = path.join(dir, uniqueName);
  if (fileObj.mv) {
    await fileObj.mv(uploadPath);
  } else if (fileObj.data) {
    await fsExtra.writeFile(uploadPath, fileObj.data);
  } else {
    throw new Error("saveUpload: no valid file handling method (mv/data) on file object");
  }
  return `${safeSub}/${uniqueName}`;
}

const ConsumerDocument = db.consumerDocument;

/**
 * Store/replace a consumer-level document (KYC). One row per (user_id,
 * categoryId): re-uploading the same type replaces the file. Used so KYC docs
 * live on the consumer and are reused across verticals instead of re-asked per
 * policy.
 */
async function upsertConsumerDocument(user_id, categoryId, file) {
  if (!user_id || !categoryId || !file) return null;
  const existing = await ConsumerDocument.findOne({ where: { user_id, categoryId } });
  if (existing) {
    existing.file = file;
    await existing.save();
    return existing;
  }
  return ConsumerDocument.create({ user_id, categoryId, file });
}

module.exports = { ensureCategoryMapping, ConsumerDocument, upsertConsumerDocument, saveUpload, Blog, BuilderUser, BuildingManager, CTRL_DIR, CancelLoan, Category, Disburse, DisbursementLoan, DocumentSelectedLoan, EmployeeMediclaim, FamilyMember, Inqueryuser, LifeInsurance, LifeInsuranceDocument, LoginLoan, Mediclaim, MediclaimCompany, MediclaimProduct, Op, PartPaymentLoan, PreviousPolicies, QueryLoan, RunningPolicies, SanctionLoan, Sequelize, Unit, UnitCategoryDetail, UnitCategoryList, User, Wing, authConfig, builderConsumer, codeDetail, companyType, consumerRoleMapping, createNotification, db, documents, dotenvParseVariables, env, floor, fs, fsExtra, fsSync, hasMeaningfulPreviousPolicyData, jwt, loanConfiguration, loanUser, moment, nodemailer, path, policyPlan, policyType, property, references, unit_category_list, userCatergory, uuidv4, vehcileRunningPolicy, vehiclePreviousPolicy, vehicleUser, vehicle_document, vehicles };
